export const PREGNANCY_DAYS = 280;
export const KICK_GOAL = 10;

export const detailedWeeks = {
  id: {
    weeks: [
      "","","","","Seukuran Biji Poppy. Janin sedang menempel pada dinding rahim. Pembentukan tabung saraf dimulai.",
      "Seukuran Biji Apel. Jantung bayi mulai berdetak! Tabung saraf mulai menutup.",
      "Seukuran Kacang Polong. Cikal bakal hidung, mulut, dan telinga mulai terbentuk.",
      "Seukuran Blueberry. Kepala bayi lebih besar dibanding tubuhnya. Tunas lengan dan kaki mulai tumbuh.",
      "Seukuran Raspberry. Bibir atas dan hidung terbentuk. Jantung berdetak cepat 150-170 bpm.",
      "Seukuran Buah Zaitun. Mata bayi telah terbentuk, otot mulai merespons pergerakan kecil.",
      "Seukuran Stroberi. Tulang rawan mulai terbentuk menjadi tulang keras. Ginjal memproduksi urine.",
      "Seukuran Jeruk Nipis. Bayi mulai mengepalkan tangan dan jari kaki sudah terpisah dari selaputnya.",
      "Seukuran Buah Plum. Organ utama sudah terbentuk lengkap. Refleks mengisap mulai muncul.",
      "Seukuran Lemon. Bayi mulai bergerak perlahan meskipun Bunda belum bisa merasakannya.",
      "Seukuran Buah Persik. Bayi mulai berlatih otot wajahnya dengan mengerutkan kening atau menyipitkan mata.",
      "Seukuran Apel. Bayi dapat merasakan cahaya dari luar rahim. Kulit masih sangat tipis.",
      "Seukuran Alpukat. Sistem peredaran darah dan saluran kemih mulai berfungsi sepenuhnya.",
      "Seukuran Bawang Bombay. Tulang bayi menyerap kalsium untuk semakin kuat. Bayi merespons suara.",
      "Seukuran Ubi Jalar. Telimga sudah berada di posisi yang sempurna. Tali pusar semakin tebal.",
      "Seukuran Mangga. Vernix caseosa (lapisan putih penutup kulit) mulai menyelimuti bayi untuk melindunginya.",
      "Seukuran Pisang. Bunda mungkin merasakan tendangan lembut (quickening). Bayi mulai menelan cairan ketuban.",
      "Seukuran Wortel. Alis dan kelopak mata bayi terbentuk penuh. Sumsum tulang mulai memproduksi darah.",
      "Seukuran Pepaya Kecil. Indera perasa berkembang, bayi bisa mengecap rasa makan Bunda dari cairan ketuban.",
      "Seukuran Terong Besar. Paru-paru bayi mulai memproduksi surfaktan untuk persiapan bernapas.",
      "Seukuran Jagung. Otak bayi berkembang pesat. Bayi mengatur posisi yang nyaman.",
      "Seukuran Kembang Kol. Bayi mulai bertumbuh menjadi gempal (lemak mulai terkumpul).",
      "Seukuran Timun Jepang. Mata bayi merespons kedipan. Denyut jantung bayi menurun sedikit seiring pertumbuhan tubuh.",
      "Seukuran Kubis Hijau. Pola tidur dan bangun bayi mulai makin teratur dan panjang.",
      "Seukuran Terong Ungu Besar. Bulu halus (lanugo) yang menutupi kulit bayi perlahan mulai rontok.",
      "Seukuran Labu Acorn. Otonomi tubuh makin baik mengatur suhu, bersiap lahir.",
      "Seukuran Kubis Besar. Kuku bayi sudah terbentuk sempurna di jari tangan dan kaki.",
      "Seukuran Kelapa. Bayi bisa menyerap zat besi, kalsium, dan fosfor dari Bunda untuk perkuatan akhir.",
      "Seukuran Bengkuang. Sebagian besar kerangka janin mengeras, walau tulang kepala masih lunak agar mudah saat lahir.",
      "Seukuran Nanas Besar. Ketuban berada pada volume terbesarnya.",
      "Seukuran Melon Blewah. Antibodi Bunda ditransfer ke bayi untuk memberikan kekebalan awal pasca lahir.",
      "Seukuran Buah Melon. Ginjal dan hati bayi sudah matang sepenuhnya.",
      "Seukuran Sawi Hijau Panjang. Kepala bayi mulai turun ke panggul Bunda (engaging).",
      "Seukuran Semangka Kecil. Paru-paru bayi kini sudah matang. Bayi mempraktikkan bernapas.",
      "Seukuran Labu Musim Dingin. Pegangan bayi semakin erat.",
      "Seukuran Nangka Kecil. Bayi dipenuhi lapisan lemak siap menjaga panas tubuh saat lahir.",
      "Seukuran Buah Labu. Bayi sudah cukup umur! Selamat menanti kehadiran si buah hati."
    ],
    symptoms: [
      "","","","","Bercak darah akibat implantasi & kram perut ringan.",
      "Morning sickness, mudah lelah, dan payudara membengkak.",
      "Sering buang air kecil dan perubahan suasana hati (mood swing).",
      "Mual makin terasa, peningkatan air liur, dan nafsu makan fluktuatif.",
      "Indera penciuman sangat tajam. Hidung bisa sering tersumbat.",
      "Kelelahan ekstrem. Perasaan kembung atau sembelit mulai muncul.",
      "Pusing karena aliran darah meningkat.",
      "Sembelit, pusing ringan, dan kulit berjerawat akibat hormon.",
      "Mual biasanya mulai berkurang. Garis hitam di perut (linea nigra) mulai muncul.",
      "Energi mulai kembali, tetapi risiko stretch mark mulai ada.",
      "Sakit punggung ringan dan perubahan ukuran payudara yang lebih drastis.",
      "Nyeri ligamen bundar (round ligament pain) saat perut makin membesar.",
      "Sembelit dan hidung tersumbat masih bisa mengganggu.",
      "Meningkatnya nafsu makan dan mungkin pegal pada pinggang.",
      "Sakit kepala sesekali dan kadang pusing saat bangkit.",
      "Keluhan kelelahan trimester 1 umumnya hilang.",
      "Rasa gerah berlebih dan pegal panggul.",
      "Muncul varises dan kram kaki di malam hari.",
      "Perut yang membesar kadang memicu rasa gatal di area pusar.",
      "Keputihan mungkin meningkat. Pastikan jaga kebersihan.",
      "Heartburn (asam lambung) saat berbaring.",
      "Wasir (hemoroid) ringan dan gusi mudah berdarah.",
      "Pergerakan bayi sangat terasa, mungkin membuat Bunda sering kaget.",
      "Kelelahan mulai kembali. Nyeri di tulang rusuk akibat tendangan bayi.",
      "Sembelit makin sering dan nyeri punggung yang butuh banyak istirahat.",
      "Kontraksi Braxton Hicks (palsu) mungkin mulai sesekali muncul.",
      "Susah tidur (insomnia). Cari posisi tidur ternyaman miring ke kiri.",
      "Perubahan mood kembali karena kelelahan, dan napas pendek/sesak.",
      "Kulit terasa meregang dan gatal, ulasan krim pelembab penting.",
      "Kolostrum (ASI awal) mungkin bocor dari payudara Bunda.",
      "Kaki makin bengkak, batasan asupan garam dan sering angkat kaki.",
      "Tangan sering kesemutan. Coba gerakkan perlahan saat istirahat.",
      "Asam lambung agak berkurang jika bayi sudah turun ke panggul.",
      "Tekanan di panggul sangat besar. Sering pipis makin menjadi rintangan.",
      "Sembelit atau wasir kembali menyerang, perbanyak cairan Bunda.",
      "Kontraksi palsu makin sering. Mulai bedakan dengan kontraksi asli.",
      "Keluarnya lendir/bercak dari serviks (bloody show).",
      "Napas lega karena bayi turun, namun area pinggul sangat pegal.",
      "Ketuban bisa pecah kapan saja. Segera hubungi dokter!"
    ],
    advices: [
      "","","","","Mulai konsumsi asam folat secara rutin 400mcg/hari.",
      "Hindari asap perokok aktif maupun pasif.",
      "Makan porsi kecil-kecil tapi sering untuk redakan mual.",
      "Cukupi air setidaknya 2 liter sehari.",
      "Siapkan camilan kering seperti biskuit di meja nakas.",
      "Lakukan meditasi atau yoga santai 15 menit.",
      "Pilih bra yang lebih besar dan menyokong dengan baik.",
      "Eksplorasi makanan tinggi zat besi seperti sayuran hijau gelap.",
      "Mulai pijat perut Bunda dengan lotion/oil mencegah stretch mark.",
      "Buat jadwal kontrol trimester pertama ke bidan/dokter kandungan.",
      "Pertahankan olahraga ringan seperti jalan pagi.",
      "Jika hidung mampet, gunakan pelembab udara (humidifier).",
      "Tidur telentang berlama-lama sebaiknya mulai dihindari, belajar miring ke kiri.",
      "Sediakan bantal penyangga tambahan (pregnancy pillow) untuk tidur.",
      "Gunakan sepatu yang nyaman tanpa hak tinggi.",
      "Porsi makan bertambah, pastikan tetap gizi seimbang bukan sekadar karbo.",
      "Kunjungi dokter gigi jika gusi sering berdarah saat sikat gigi.",
      "Lakukan teknik relaksasi saat mengalami kram kaki malam hari.",
      "Jaga postur punggung saat duduk dan berdiri. Jangan membungkuk.",
      "Perhatikan asupan omega 3 untuk kecerdasan janin.",
      "Jangan langsung tidur setelah makan, berikan jeda setidaknya 2 jam.",
      "Tingkatkan makanan tinggi serat untuk mengurangi sembelit dan wasir.",
      "Kenali pola pergerakan harian bayi, mulai rasakan polanya.",
      "Jika kram terasa menusuk, segera duduk/istirahatkan badan.",
      "Kurangi makan pedas jika asam lambung sering kambuh.",
      "Gunakan sabuk penyangga perut membatasi guncangan bila dirasa sangat berat.",
      "Pertimbangkan untuk mengikuti senam kehamilan dengan pemandu profesional.",
      "Jangan gunakan cairan pencuci organ intim, gunakan sabun biasa saja dari luar.",
      "Terus pantau hitungan tendangan bayi harian melalui BundaCare.",
      "Ambil kelas laktasi (menyusui) jika ada dan mulai beli perlengkapan bayi.",
      "Cek list tas persalinan (Hospital Bag). Siapkan tepat dekat pintu keluar.",
      "Jika merencanakan aqiqah/pesta sambut bayi, ini waktu pas mencicil perencanaan.",
      "Pijat lembut perineum untuk fleksibelitas saat melahirkan bisa dipelajari.",
      "Gunakan kompres hangat untuk area panggul/pinggang yang pegal.",
      "Ketahui tanda bahaya ketuban pecah dini. Jangan abaikan rembesan air.",
      "Pahami tanda kontraksi sebenarnya (makin teratur dan sering).",
      "Mulai latih pernapasan untuk melahirkan (tarik napas panjang-hembuskan rileks).",
      "Tentukan rute terbaik ke klinik bersalin dan kenali kemacetan sekitarnya.",
      "Tetap bawa buku KIA/Buku Pink ke manapun Bunda pergi saat dekat HPL.",
      "Tetap berjalan santai sesekali memicu panggul, atau pantul-pantul perlahan di birthing ball."
    ]
  },
  en: {
    weeks: [
      "","","","","Size of a Poppy Seed. The embryo implants into your uterine wall. Neural tube formation begins.",
      "Size of an Apple Seed. Baby's heart starts beating! The neural tube begins to close.",
      "Size of a Sweet Pea. Buddings of the nose, mouth, and ears begin to form.",
      "Size of a Blueberry. The head is much larger than the body. Arm and leg buds start growing.",
      "Size of a Raspberry. Upper lip and nose form. Heart beats at about 150-170 bpm.",
      "Size of a Green Olive. Baby's eyes have formed, muscles start responding to slight movements.",
      "Size of a Strawberry. Cartilage begins hardening into bone. Kidneys produce urine.",
      "Size of a Lime. Baby starts clenching fists and toes are separated from their webbing.",
      "Size of a Plum. Major organs are fully formed. The sucking reflex begins to appear.",
      "Size of a Lemon. Baby starts moving slowly although you probably won't feel it yet.",
      "Size of a Peach. Baby begins exercising facial muscles by frowning or squinting.",
      "Size of an Apple. Baby can sense light from outside the womb. Skin is still very thin.",
      "Size of an Avocado. Circulatory and urinary systems start functioning completely.",
      "Size of an Onion. Baby's bones absorb calcium to get stronger. Baby responds to sounds.",
      "Size of a Sweet Potato. Ears move to their proper position. The umbilical cord thickens.",
      "Size of a Mango. Vernix caseosa (a white waxy coating) covers the baby to protect them.",
      "Size of a Banana. You might feel gentle kicks (quickening). Baby starts swallowing amniotic fluid.",
      "Size of a Carrot. Baby's eyebrows and eyelids are fully formed. Bone marrow produces blood.",
      "Size of a Small Papaya. Sense of taste develops, baby can taste your meals from amniotic fluid.",
      "Size of a Large Eggplant. Baby's lungs start producing surfactant to prepare for breathing.",
      "Size of an Ear of Corn. Baby's brain is developing rapidly. Baby finds a comfortable position.",
      "Size of a Cauliflower. Baby starts getting plumper as fat accumulates.",
      "Size of a Zucchini. Baby's eyes respond to blinking. Heart rate decreases slightly as they grow.",
      "Size of a Green Cabbage. Baby's sleep/wake cycles become more regular and longer.",
      "Size of a Large Eggplant. Fine hair (lanugo) covering baby's skin slowly begins to shed.",
      "Size of an Acorn Squash. Better body autonomy regulates temperature, preparing for birth.",
      "Size of a Large Cabbage. Baby's nails are perfectly formed on fingers and toes.",
      "Size of a Coconut. Baby absorbs iron, calcium, and phosphorus from you for final strengthening.",
      "Size of a Jicama. Most of the fetal skeleton hardens, though the skull is still soft for childbirth.",
      "Size of a Large Pineapple. Amniotic fluid is at its maximum volume.",
      "Size of a Cantaloupe. Your antibodies are transferred to baby, providing initial immunity.",
      "Size of a Honeydew Melon. Baby's kidneys and liver are fully mature.",
      "Size of a Creeping Mustard. Baby's head starts descending into your pelvis (engaging).",
      "Size of a Small Watermelon. Baby's lungs are now mature. Baby practices breathing.",
      "Size of a Winter Squash. Baby's grasp gets tighter.",
      "Size of a Small Jackfruit. Baby is covered in fat layers ready to keep warm at birth.",
      "Size of a Pumpkin. Baby is full-term! Congratulations on expecting your little one soon."
    ],
    symptoms: [
      "","","","","Implantation bleeding & mild abdominal cramps.",
      "Morning sickness, fatigue, and swollen breasts.",
      "Frequent urination and mood swings.",
      "Nausea may worsen, increased saliva, and fluctuating appetite.",
      "Heightened sense of smell. Nose may frequently feel blocked.",
      "Extreme fatigue. Bloating or constipation may start.",
      "Dizziness due to increased blood flow.",
      "Constipation, mild dizziness, and acne from hormones.",
      "Nausea usually starts to fade. The dark line on your belly (linea nigra) may appear.",
      "Energy starts returning, but stretch mark risks emerge.",
      "Mild back pain and more noticeable changes in breast size.",
      "Round ligament pain as your belly grows.",
      "Constipation and a stuffy nose might still bother you.",
      "Increased appetite and possibly lower back aches.",
      "Occasional headaches and dizziness when standing up quickly.",
      "First-trimester fatigue symptoms generally disappear.",
      "Excessive feeling of warmth and pelvic ache.",
      "Varicose veins and nighttime leg cramps may appear.",
      "Growing belly can sometimes trigger itching around the navel.",
      "Vaginal discharge may increase. Maintain good hygiene.",
      "Heartburn when lying down.",
      "Mild hemorrhoids and gums that bleed easily.",
      "Baby movements are very noticeable, might often startle you.",
      "Fatigue begins returning. Rib pain from baby's kicks.",
      "Constipation becomes more frequent and back pain requires plenty of rest.",
      "Braxton Hicks (false) contractions may occasionally start.",
      "Trouble sleeping (insomnia). Find a comfy sleep position on your left side.",
      "Mood swings return due to exhaustion, alongside short/shallow breath.",
      "Skin feels stretched and itchy; applying moisturizing cream is essential.",
      "Colostrum (early milk) might leak from your breasts.",
      "Feet get more swollen; limit salt intake and elevate often.",
      "Hands often get tingly (carpal tunnel). Move them gently when resting.",
      "Heartburn slightly decreases once baby drops into the pelvis.",
      "Immense pressure in the pelvis. Frequent urination becomes a major hurdle.",
      "Constipation or hemorrhoids attack again, increase your fluids.",
      "False contractions happen more often. Start differentiating from real ones.",
      "Discharge of mucus/spotting from cervix (bloody show).",
      "Easier breathing since baby descends, but hip area is extremely achy.",
      "Water could break anytime. Contact your doctor immediately!"
    ],
    advices: [
      "","","","","Start taking your folic acid routinely 400mcg/day.",
      "Avoid active and passive smoking.",
      "Eat smaller, more frequent meals to relieve nausea.",
      "Drink at least 2 liters of water daily.",
      "Prepare dry snacks like crackers on your nightstand.",
      "Practice meditation or relaxing yoga for 15 minutes.",
      "Choose a larger bra offering good support.",
      "Explore iron-rich foods like dark leafy greens.",
      "Begin massaging your belly with lotion/oil to prevent stretch marks.",
      "Schedule your first-trimester appointment with the OB/GYN.",
      "Maintain light exercise like morning walks.",
      "If your nose is clogged, use a humidifier.",
      "Avoid sleeping on your back for long; start sleeping on your left side.",
      "Get a pregnancy pillow for extra support during sleep.",
      "Wear comfortable shoes without high heels.",
      "Appetite increases, ensure balanced nutrition—not just carbs.",
      "Visit a dentist if your gums bleed often while brushing.",
      "Practice relaxation techniques for nighttime leg cramps.",
      "Mind your back posture sitting and standing. Do not slouch.",
      "Pay attention to omega 3 intake for fetal brain development.",
      "Do not sleep right after eating, give it at least 2 hours.",
      "Increase high-fiber foods to reduce constipation and hemorrhoids.",
      "Familiarize yourself with your baby's daily movement patterns.",
      "If the cramp feels sharp, sit down / rest immediately.",
      "Reduce spicy foods if heartburn frequently relapses.",
      "Use a maternity support belt if your belly feels too heavy.",
      "Consider joining professional prenatal classes.",
      "Do not use intimate washes; stick to regular mild soap for outer areas.",
      "Keep monitoring daily kicks via BundaCare.",
      "Take lactation (breastfeeding) classes if available and buy baby gear.",
      "Finalize your Hospital Bag checklist. Place it near the door.",
      "If planning a baby shower/welcome party, it's a good time to prep.",
      "You can learn gentle perineal massage for childbirth flexibility.",
      "Use a warm compress for a sore pelvis/lower back area.",
      "Know the danger signs of premature water break. Don't ignore leaks.",
      "Understand true contraction signs (getting more regular and frequent).",
      "Start practicing labor breathing (deep breath in - relax exhale).",
      "Determine the best route to the maternity clinic and know local traffic.",
      "Keep your pregnancy record book/file on you wherever you go near EDD.",
      "Keep taking relaxing walks to stimulate your pelvis, or gently bounce on a birthing ball."
    ]
  }
};

export const i18nData: Record<string, Record<string, string>> = {
  id: {
    headerSubtitle: "care made easy.",
    setupTitle: "Halo, Bunda!",
    setupDesc: "Masukkan Hari Pertama Haid Terakhir (HPHT) untuk memulai.",
    hphtLabel: "Tanggal HPHT",
    calcBtn: "Hitung Akurat",
    pregAgeLabel: "Usia Kehamilan Bunda",
    startLabel: "Mulai",
    birthLabel: "Lahir",
    eddLabel: "HPL (Perkiraan)",
    conceptionLabel: "Tanggal Konsepsi",
    conceptionDesc: "Awal mula perjalanan",
    readTipsBtn: "Baca Tips & Persiapan",
    weeklySummaryTitle: "Ringkasan Minggu Ini",
    fetalSizeTitle: "Ukuran Janin",
    weeklyTipTitle: "Fokus Minggu Ini",
    weeklyMilestoneTitle: "Milestone Mendekat",
    symptomTitle: "Gejala & Waspada",
    adviceTitle: "Saran untuk Bunda",
    milestoneTitle: "Milestone Penting",
    growthChartTitle: "Grafik Pertumbuhan Janin",
    growthChartSubtitle: "Perbandingan panjang janin dengan rata-rata (cm)",
    wearableTitle: "Koneksi Smartwatch",
    wearableDesc: "Sambungkan smartwatch Bunda untuk memantau detak jantung dan tidur.",
    wearableConnectBtn: "Hubungkan Perangkat",
    wearableTutorialBtn: "Lihat Tutorial Koneksi",
    maternalHrLabel: "Detak Jantung Ibu",
    fetalHrLabel: "Estimasi DJJ Janin",
    aiEstimateLabel: "AI Est",
    sleepLabel: "Kualitas Tidur",
    tipsTitle: "Tips Harian Bunda",
    aiChatBannerTitle: "Tanya Asisten AI",
    aiChatBannerDesc: "Tanyakan apapun seputar kehamilan dan tips perawatan",
    kicksTitle: "Penghitung Gerakan",
    kicksDisclaimer: "Trimester 3 (28 Minggu+)",
    kicksGoal: "Target Harian: ",
    kicksBtn: "CATAT GERAKAN",
    checkupHomeTitle: "Jadwal Check-up",
    checkupHomeSubtitle: "Rekap Kunjungan",
    searchHospitalBtn: "Cari RS/Klinik Bersalin Terdekat",
    usgHomeTitle: "Rekap USG",
    usgHomeSubtitle: "Riwayat Perkembangan",
    usgGuideTitle: "Panduan Membaca USG",
    crlDesc: "Panjang janin dari puncak kepala hingga pinggul (bokong). Umumnya digunakan di trimester pertama dan paling akurat untuk menentukan usia kehamilan.",
    gaDesc: "Perkiraan usia kehamilan berdasarkan pengukuran USG, biasanya diukur dalam minggu dan hari (misal: 12W3D = 12 minggu 3 hari).",
    eddDesc: "Perkiraan hari lahir / HPL (Hari Perkiraan Lahir) berdasarkan pengukuran USG. Terkadang ditulis sebagai EDD atau EDC.",
    navHome: "Home",
    navTips: "Tips",
    navKicks: "Gerak",
    navCheckup: "Check-up",
    navUsg: "USG",
    weeksLabel: "Minggu",
    daysLabel: "Hari",
    aroundMonthsLabel: "Sekitar {m} Bulan",
    daysRemaining: "{d} hari menuju kelahiran",
    timeToMeet: "Waktunya bertemu si kecil!",
    tri1Title: "Trimester 1",
    tri1Desc: "Masa adaptasi dan pembentukan organ vital janin. Bunda mungkin mengalami mual dan kelelahan. Jaga asupan nutrisi dan asam folat ya.",
    tri2Title: "Trimester 2",
    tri2Desc: "Trimester paling nyaman! Energi mulai kembali, baby bump mulai terlihat, dan Bunda akan merasakan tendangan pertama dari sikecil.",
    tri3Title: "Trimester 3",
    tri3Desc: "Fase persiapan akhir persalinan. Janin semakin besar. Lakukan pemantauan gerakan janin dan mulai siapkan mental serta perlengkapan kelahiran.",
    m1Label: "Tes Kehamilan Akurat",
    m2Label: "Detak Jantung Pertama",
    m3Label: "Akhir Trimester 1",
    m4Label: "Organ Terbentuk Sempurna",
    m5Label: "Janin Mulai Mendengar",
    m6Label: "HPL (Hari Perkiraan Lahir)",
    tipTri1_1Title: "Atasi Mual (Morning Sickness)",
    tipTri1_1Text: "Makan dalam porsi kecil tapi sering, hindari makanan berbau menyengat, dan minum jahe hangat dapat membantu meredakan mual.",
    tipTri1_2Title: "Asam Folat Penting",
    tipTri1_2Text: "Pastikan asupan folat dan vitamin prenatal cukup untuk mendukung pembentukan tabung saraf janin di fase krusial ini.",
    tipTri2_1Title: "Aktif Bergerak",
    tipTri2_1Text: "Energi Bunda mulai kembali. Senam hamil, yoga, atau jalan kaki ringan bantu jaga stamina dan kurangi sakit punggung.",
    tipTri2_2Title: "Posisi Tidur Miring",
    tipTri2_2Text: "Mulai biasakan tidur menghadap ke kiri. Ini memaksimalkan aliran darah dan nutrisi menuju plasenta.",
    tipTri3_1Title: "Pantau Gerakan Janin",
    tipTri3_1Text: "Gunakan fitur Penghitung Gerakan di aplikasi ini untuk memastikan bayi tetap aktif minimal 10 kali dalam 2 jam.",
    tipTri3_2Title: "Persiapan Persalinan",
    tipTri3_2Text: "Mulai kemas 'Hospital Bag' dan pelajari teknik pernapasan untuk persalinan yang lebih tenang.",
    tip1Title: "Nutrisi Kehamilan",
    tip1Text: "Pastikan Bunda mengonsumsi cukup asam folat dan zat besi untuk mencegah anemia dan mendukung perkembangan saraf bayi.",
    tip4Title: "Hindari Stres",
    tip4Text: "Dengarkan musik relaksasi atau curhat dengan Ayah. Ketenangan Bunda sangat berpengaruh pada kenyamanan janin.",
    aiBotName: "BundaCare AI",
    aiBotStatus: "Siap membantu Bunda",
    aiChatInputPlaceholder: "Ketik pertanyaan Bunda di sini...",
    aiWelcomeMsg: "Halo Bunda! Saya asisten AI. Ada yang bisa saya bantu terkait informasi kehamilan atau tips perawatan kesehatan hari ini?",
    aiLoading: "Mengetik jawaban...",
    aiError: "Maaf, gagal mendapatkan jawaban dari AI. Coba lagi nanti.",
    addCheckupTitle: "Jadwal Check-up",
    checkupClinicLabel: "Nama RS/Klinik *",
    checkupDateLabel: "Tanggal *",
    checkupDoctorLabel: "Nama Dokter",
    checkupNoteLabel: "Catatan / Hasil Pemeriksaan",
    saveBtn: "Simpan",
    addUsgTitle: "Simpan Hasil USG",
    usgPhotoLabel: "Foto USG",
    toastSelectHpht: "Pilih tanggal HPHT dulu ya, Bunda",
    toastFutureHpht: "Tanggal HPHT tidak bisa di masa depan!",
    toastPastHpht: "Tanggal HPHT terlalu lama (lebih dari 42 minggu).",
    toastUpdated: "Data kehamilan berhasil diperbarui!",
    toastKicksGoal: "Hore! Target 10 tendangan harian tercapai! 🎉",
    toastKickAdded: "Gerakan dicatat!",
    confirmResetKicks: "Yakin ingin mereset hitungan gerakan hari ini?",
    toastKicksReset: "Hitungan di-reset",
    toastCheckupReq: "Isi nama klinik dan tanggal",
    toastCheckupSaved: "Jadwal check-up tersimpan!",
    toastCheckupDeleted: "Jadwal check-up dihapus!",
    toastUsgReq: "Isi tanggal USG",
    toastUsgSaved: "Data USG tersimpan!",
    toastUsgDeleted: "Data USG dihapus!",
    confirmResetData: "Apakah Bunda yakin ingin menghapus data HPHT dan memulai dari awal?",
    aboutTitle: "Tentang Aplikasi",
    aboutDesc1: "BundaCare adalah asisten kehamilan cerdas yang dirancang khusus untuk mendampingi calon ibu selama masa kehamilan hingga masa persiapan persalinan dengan aman, mudah dan terpercaya.",
    aboutDesc2: "Dengan fitur pemantauan perkembangan janin, penghitung gerakan, pengingat jadwal check-up, dan dukungan AI (Gemini), BundaCare bertujuan untuk memberikan rasa aman serta informasi pendukung kapanpun Bunda membutuhkannya.",
    aboutFooterTitle: "Dibuat dengan cinta untuk para Ibu.",
    settingsDisplay: "Tampilan",
    settingsTheme: "Pilih Tema Warna Utama",
    settingsCustomColor: "Warna Kustom",
    settingsLanguage: "Bahasa",
    settingsPersona: "Karakter Asisten AI",
    personaDefault: "Ramah & Empati (Default)",
    personaFormal: "Formal & Profesional",
    personaCasual: "Santai & Menyenangkan",
    logoutBtn: "Keluar",
    aboutBtn: "Tentang BundaCare",
    emergencyTitle: "Kontak Darurat",
    ambulanceLabel: "Ambulan / Medis",
    policeLabel: "Polisi / Darurat",
    personalContactsTitle: "Kontak Personal",
    addContactTitle: "Tambah Kontak Baru",
    emNamePlaceholder: "Nama (Misal: Suami, Dokter)",
    emPhonePlaceholder: "Nomor Telepon",
    saveContactBtn: "Simpan Kontak",
    toastContactReq: "Isi nama dan nomor telepon",
    toastContactSaved: "Kontak tersimpan!",
    toastContactDeleted: "Kontak dihapus!",
    tooltipEmergency: "Kontak Darurat",
    tooltipShare: "Bagikan",
    tooltipSettings: "Pengaturan",
    tooltipReset: "Reset Data",
    shareText: "Halo! Saat ini usia kehamilanku {w} dan {d}. Perkiraan si kecil akan lahir pada {edd}. Mohon doanya ya agar kami berdua sehat selalu! 💕 Dibagikan via BundaCare.",
    toastShareSuccess: "Berhasil dibagikan atau disalin ke clipboard!",
    toastShareFailed: "Gagal membagikan progres."
  },
  en: {
    headerSubtitle: "care made easy.",
    setupTitle: "Hello, Mom!",
    setupDesc: "Enter the First Day of your Last Menstrual Period (LMP) to begin.",
    hphtLabel: "LMP Date",
    calcBtn: "Calculate Accurately",
    pregAgeLabel: "Your Pregnancy Age",
    startLabel: "Start",
    birthLabel: "Birth",
    eddLabel: "Estimated Due Date",
    conceptionLabel: "Conception Date",
    conceptionDesc: "The beginning of the journey",
    readTipsBtn: "Read Tips & Prep",
    weeklySummaryTitle: "This Week's Summary",
    fetalSizeTitle: "Fetal Size",
    weeklyTipTitle: "Week's Focus",
    weeklyMilestoneTitle: "Upcoming Milestone",
    symptomTitle: "Symptoms & Alerts",
    adviceTitle: "Advice for You",
    milestoneTitle: "Important Milestones",
    growthChartTitle: "Fetal Growth Chart",
    growthChartSubtitle: "Comparison of fetal length with average (cm)",
    wearableTitle: "Smartwatch Connection",
    wearableDesc: "Connect your smartwatch to monitor heart rate and sleep quality.",
    wearableConnectBtn: "Connect Device",
    wearableTutorialBtn: "View Connection Tutorial",
    maternalHrLabel: "Maternal Heart Rate",
    fetalHrLabel: "Est. Fetal Heart Rate",
    aiEstimateLabel: "AI Est",
    sleepLabel: "Sleep Quality",
    tipsTitle: "Mom's Daily Tips",
    aiChatBannerTitle: "Ask AI Assistant",
    aiChatBannerDesc: "Ask anything about pregnancy and care tips",
    kicksTitle: "Kick Counter",
    kicksDisclaimer: "3rd Trimester (28+ Weeks)",
    kicksGoal: "Daily Goal: ",
    kicksBtn: "RECORD KICK",
    checkupHomeTitle: "Check-up Schedule",
    checkupHomeSubtitle: "Visit Recap",
    searchHospitalBtn: "Search Nearby Hospitals",
    usgHomeTitle: "USG Recap",
    usgHomeSubtitle: "Development History",
    usgGuideTitle: "Ultrasound (USG) Reading Guide",
    crlDesc: "Crown Rump Length. Measurement of the length of human embryos and fetuses from the top of the head (crown) to the bottom of the buttocks (rump). It is typically determined from ultrasound imagery and can be used to estimate gestational age.",
    gaDesc: "Gestational Age. The estimated age of the pregnancy based on ultrasound measurements, usually measured in weeks and days (e.g., 12W3D = 12 weeks 3 days).",
    eddDesc: "Estimated Date of Delivery. The estimated due date based on ultrasound measurements. Sometimes written as EDD or EDC.",
    navHome: "Home",
    navTips: "Tips",
    navKicks: "Kicks",
    navCheckup: "Check-up",
    navUsg: "USG",
    weeksLabel: "Weeks",
    daysLabel: "Days",
    aroundMonthsLabel: "Around {m} Months",
    daysRemaining: "{d} days until birth",
    timeToMeet: "Time to meet your little one!",
    tri1Title: "1st Trimester",
    tri1Desc: "A time of adaptation and vital organ formation. You might experience nausea and fatigue. Keep up with your nutrition and folic acid.",
    tri2Title: "2nd Trimester",
    tri2Desc: "The most comfortable trimester! Energy returns, the baby bump grows, and you'll feel the first tiny kicks.",
    tri3Title: "3rd Trimester",
    tri3Desc: "The final preparation phase. The baby is much larger. Monitor fetal movements and start preparing your mind and hospital bag.",
    m1Label: "First Positive Test",
    m2Label: "First Heartbeat",
    m3Label: "End of 1st Trimester",
    m4Label: "Organs Fully Formed",
    m5Label: "Baby Starts Hearing",
    m6Label: "Estimated Due Date",
    tipTri1_1Title: "Manage Morning Sickness",
    tipTri1_1Text: "Eat smaller, more frequent meals, avoid strong-smelling foods, and try warm ginger tea to ease nausea.",
    tipTri1_2Title: "Folic Acid is Crucial",
    tipTri1_2Text: "Ensure sufficient folate and prenatal vitamins to support the baby's neural tube formation in this critical phase.",
    tipTri2_1Title: "Stay Active",
    tipTri2_1Text: "Your energy is back! Prenatal yoga, swimming, or brisk walking helps maintain stamina and combat back pain.",
    tipTri2_2Title: "Sleep on Your Side",
    tipTri2_2Text: "Start sleeping on your left side to maximize blood flow and nutrients reaching the placenta.",
    tipTri3_1Title: "Monitor Fetal Movements",
    tipTri3_1Text: "Use the Kick Counter feature in this app to ensure your baby is active at least 10 times in 2 hours.",
    tipTri3_2Title: "Birth Preparation",
    tipTri3_2Text: "Start packing your Hospital Bag and learn breathing techniques for a calmer labor experience.",
    tip1Title: "Pregnancy Nutrition",
    tip1Text: "Ensure you consume enough folic acid and iron to prevent anemia and support your baby's neural development.",
    tip4Title: "Avoid Stress",
    tip4Text: "Listen to relaxing music or talk to your partner. Your calmness greatly affects the baby's comfort.",
    aiBotName: "BundaCare AI",
    aiBotStatus: "Ready to help you",
    aiChatInputPlaceholder: "Type your question here...",
    aiWelcomeMsg: "Hello Mom! I'm your AI assistant. How can I help you today with pregnancy info or healthcare tips?",
    aiLoading: "Typing answer...",
    aiError: "Sorry, failed to get an answer from AI. Please try again later.",
    addCheckupTitle: "Check-up Schedule",
    checkupClinicLabel: "Hospital/Clinic Name *",
    checkupDateLabel: "Date *",
    checkupDoctorLabel: "Doctor's Name",
    checkupNoteLabel: "Notes / Examination Results",
    saveBtn: "Save",
    addUsgTitle: "Save USG Result",
    usgPhotoLabel: "USG Photo",
    toastSelectHpht: "Please select your LMP date first",
    toastFutureHpht: "LMP date cannot be in the future!",
    toastPastHpht: "LMP date is too far in the past (over 42 weeks).",
    toastUpdated: "Pregnancy data updated successfully!",
    toastKicksGoal: "Yay! Daily goal of 10 kicks reached! 🎉",
    toastKickAdded: "Kick recorded!",
    confirmResetKicks: "Are you sure you want to reset today's kick count?",
    toastKicksReset: "Count reset",
    toastCheckupReq: "Please enter clinic name and date",
    toastCheckupSaved: "Check-up schedule saved!",
    toastCheckupDeleted: "Check-up schedule deleted!",
    toastUsgReq: "Please enter USG date",
    toastUsgSaved: "USG data saved!",
    toastUsgDeleted: "USG data deleted!",
    confirmResetData: "Are you sure you want to clear your LMP data and start over?",
    aboutTitle: "About App",
    aboutDesc1: "BundaCare is a smart pregnancy assistant specifically designed to accompany mothers-to-be throughout their pregnancy journey up to delivery, ensuring a safe, easy, and reliable experience.",
    aboutDesc2: "By featuring fetal development tracking, a kick counter, check-up reminders, and AI support (Gemini), BundaCare aims to provide peace of mind and supporting info whenever you need it.",
    aboutFooterTitle: "Made with love for all Mothers.",
    settingsDisplay: "Appearance",
    settingsTheme: "Choose Primary Color Theme",
    settingsCustomColor: "Custom Color",
    settingsLanguage: "Language",
    settingsPersona: "AI Assistant Persona",
    personaDefault: "Friendly & Empathetic (Default)",
    personaFormal: "Formal & Professional",
    personaCasual: "Casual & Fun",
    logoutBtn: "Logout",
    aboutBtn: "About BundaCare",
    emergencyTitle: "Emergency Contacts",
    ambulanceLabel: "Ambulance / Medical",
    policeLabel: "Police / Emergency",
    personalContactsTitle: "Personal Contacts",
    addContactTitle: "Add New Contact",
    emNamePlaceholder: "Name (e.g., Husband, Doctor)",
    emPhonePlaceholder: "Phone Number",
    saveContactBtn: "Save Contact",
    toastContactReq: "Enter name and phone number",
    toastContactSaved: "Contact saved!",
    toastContactDeleted: "Contact deleted!",
    tooltipEmergency: "Emergency Contacts",
    tooltipShare: "Share",
    tooltipSettings: "Settings",
    tooltipReset: "Reset Data",
    shareText: "Hi! My pregnancy is currently at {w} and {d}. Our little one is estimated to arrive on {edd}. Please keep us in your thoughts and prayers! 💕 Shared via BundaCare.",
    toastShareSuccess: "Successfully shared or copied to clipboard!",
    toastShareFailed: "Failed to share progress."
  }
};
